# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-28 04:37
from __future__ import unicode_literals

import app_data.fields
from django.db import migrations, models
import django.db.models.deletion
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RSSFeedConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='Type')),
                ('namespace', models.CharField(default=None, max_length=100, unique=True, verbose_name='Instance namespace')),
                ('app_data', app_data.fields.AppDataField(default='{}', editable=False)),
                ('feed_type', models.CharField(choices=[('Rss201rev2Feed', 'RSS 2.01.'), ('RssUserland091Feed', 'RSS 0.91.'), ('Atom1Feed', 'Atom 1.0.')], default='Rss201rev2Feed', max_length=32, verbose_name='feed type')),
                ('model', models.CharField(choices=[('article', 'Article'), ('event', 'Event'), ('vacancy', 'Vacancy')], default='article', max_length=32, verbose_name='feed model')),
                ('section', models.CharField(blank=True, max_length=32, null=True, verbose_name='feed section slug')),
                ('limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='feed limit')),
            ],
            options={
                'verbose_name': 'RSS Feed',
                'verbose_name_plural': 'RSS Feeds',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RSSFeedConfigTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('app_title', models.CharField(max_length=234, verbose_name='name')),
                ('title', models.CharField(max_length=255, verbose_name='feed title')),
                ('description', models.CharField(max_length=255, verbose_name='feed description')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='js_rss_feed.RSSFeedConfig')),
            ],
            options={
                'verbose_name': 'RSS Feed Translation',
                'db_table': 'js_rss_feed_rssfeedconfig_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.AlterUniqueTogether(
            name='rssfeedconfigtranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
